apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
  - ../../base

namespace: thor-firewall-prod

patchesStrategicMerge:
  - replicas-patch.yaml

images:
  - name: thor-firewall/control-plane
    newTag: "stable"
  - name: thor-firewall/ml-serving
    newTag: "stable"
  - name: thor-firewall/dashboard
    newTag: "stable"
