apiVersion: apps/v1
kind: Deployment
metadata:
  name: control-plane
  namespace: thor-firewall-prod
spec:
  replicas: 3
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dashboard
  namespace: thor-firewall-prod
spec:
  replicas: 3
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ml-serving
  namespace: thor-firewall-prod
spec:
  replicas: 2
